version: "3.7"

volumes:
  grafana-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/xvdf1/grafana-data
  prometheus-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/xvdf1/prometheus-data
  loki-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/xvdf1/loki-data

services:
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=1y"
      - "--web.enable-lifecycle"

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    ###### linux
    command:
      - "--path.rootfs=/host"
    pid: host
    volumes:
      - "/:/host:ro,rslave"

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
      - loki-data:/loki
    ports:
      - 3100:3100
    command:
      - "-config.file=/mnt/config/loki-config.yml"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  # app_example:
  #   image: quay.io/brancz/prometheus-example-app:v0.3.0
  #   container_name: app_example
  #   restart: unless-stopped
  #   ports:
  #     - 80:8080
